version: "3"
services:
#### postgres ####
  postgres:
    image: postgres:latest
    container_name: postgres1
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
    restart: unless-stopped
#### Currencies API ####
  currencies:
    image: currencies-api:latest
    container_name: currencies
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - ip=postgres
    restart: unless-stopped
    depends_on:
      - postgres